---

- name: Get MySQL version using mysql CLI
  ansible.builtin.shell: "mysql --login-path=root -e 'SELECT VERSION();' -s -N"
  become_user: "bharat"
  register: mysql_version_output

- name: Show MySQL version
  ansible.builtin.debug:
    msg: "MySQL version on {{ inventory_hostname }}: {{ mysql_version_output.stdout }}"

- name: Get MySQL version
  community.mysql.mysql_query:
    login_user: "root"
    login_host: "localhost"
    login_db: "information_schema"
    query: "SELECT VERSION();"
  register: query_result

- name: Show MySQL version
  ansible.builtin.debug:
    msg: "MySQL version on {{ inventory_hostname }}: {{ query_result }}"


- name: Convert query results to CSV
  ansible.builtin.copy:
    dest: "{{ output_file }}"
    content: |
      {% for row in query_result.results %}
      {% for key, value in row.items() %}
      {{ key }}: {{ value }}{% if not loop.last %}, {% endif %}
      {% endfor %}
      {% if not loop.last %}\n{% endif %}
      {% endfor %}
  when: query_result.results | length > 0
  delegate_to: "{{ inventory_hostname }}"

- name: Print message
  ansible.builtin.debug:
    msg: "Query results saved to {{ output_file }}"
  when: query_result.results | length > 0
  delegate_to: "{{ inventory_hostname }}"
