---
# tasks file for Httpd

  - name: install httpd
    yum:
      name: "{{ pck }}"
      state: latest
    notify: restart
  
  - name: install nginx
    yum:
      name: "{{ pck2 }}"
      state: latest
    notify: restart
