---
# tasks file for Httpd

  - name: install httpd
    yum:
      name: "{{ pck }}"
      state: latest
    notify: restart
  
  - name: install nginx
    yum:
      name: "{{ pck2 }}"
      state: latest
    notify: restart

  - name: folder creation
    file:
      dest: /root/test.txt
      state: touch
  
  - name: folder creation
    copy:
      content: '# This file is belonogs to srujana'
      dest: /root/test.txt

