
---
- name: Display the collected alerts
  ansible.builtin.command: cat data.json 
  delegate_to: localhost
  register: json_content
  run_once: true

- name: Debug parsed data structure
  debug:
    var: json_content.stdout

- name: Parse JSON content
  set_fact:
    parsed_json: "{{ json_content.stdout | from_json }}"

- name: Filter relevant alerts
  set_fact:
    relevant_alerts: "{{ parsed_json.parse_data['items'] | list }}"

# - name: Prepare filtered alerts for logging with current date
#   set_fact:
#     logic_monitor_email_body: |
#       | Date                 | Ask Comment  | Monitor Object Name   | Resource Template Name  |
#       |----------------------|--------------|-----------------------|-------------------------|
#       {% for item in relevant_alerts %}
#       | {{ ansible_date_time.iso8601 }} | {{ item.askComment | default('') }}{{ ' ' * (12 - item.askComment | length) }} | {{ item.monitorObjectName | default('') }}{{ ' ' * (21 - item.monitorObjectName | length) }} | {{ item.resourceTemplateName | default('') }}{{ ' ' * (23 - item.resourceTemplateName | length) }} |
#       {% endfor %}
#  when: relevant_alerts | length > 0

- name: Prepare filtered alerts for email in HTML table format
  set_fact:
    logic_monitor_email_body: |
      <html>
        <head>
          <style>
            table {
              width: 100%;
              border-collapse: collapse;
              font-family: Arial, sans-serif;
              font-size: 14px;
            }
            th, td {
              border: 1px solid #dddddd;
              text-align: left;
              padding: 8px;
            }
            th {
              background-color: #f2f2f2;
            }
            tr:nth-child(even) {
              background-color: #f9f9f9;
            }
          </style>
        </head>
        <body>
          <p>Here are the filtered alerts:</p>
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Ask Comment</th>
                <th>Monitor Object Name</th>
                <th>Resource Template Name</th>
              </tr>
            </thead>
            <tbody>
              {% for item in relevant_alerts %}
              <tr>
                <td>{{ ansible_date_time.iso8601 }}</td>
                <td>{{ item.askComment | default('') }}</td>
                <td>{{ item.monitorObjectName | default('') }}</td>
                <td>{{ item.resourceTemplateName | default('') }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </body>
      </html>
  when: relevant_alerts | length > 0
