
---
- name: Display the collected alerts
  ansible.builtin.command: cat data.json 
  delegate_to: localhost
  register: json_content
  run_once: true

- name: Debug parsed data structure
  debug:
    var: json_content.stdout

- name: Debug the parsed data's structure and keys
  debug:
    msg: "{{ json_content.parse_data }}"

- name: Filter relevant alerts
  set_fact:
    relevant_alerts: "{{ json_content.stdout | selectattr('askComment', 'search', '^(EVT|INC)') | list }}"

# - name: Filter items where askComment starts with 'EVT' or 'INC'
#   set_fact:
#     filtered_items: "{{ parsed_data.parse_data.items | selectattr('askComment', 'search', '^EVT|^INC') | list }}"

- name: Display filtered items
  debug:
    msg: >
      Ask Comment: {{ item.askComment }}
      Monitor Object Name: {{ item.monitorObjectName }}
      Resource Template Name: {{ item.resourceTemplateName }}
  with_items: "{{ filtered_items }}"
  delegate_to: localhost
  run_once: true

