
---
- name: Read JSON file
  slurp:
    src: data.json
  register: json_content
  delegate_to: localhost
  run_once: true

- name: Parse JSON content
  set_fact:
    parsed_data: "{{ json_content['items']}}"

- name: Display all items
  debug:
    msg: >
      Ask Comment: {{ item.askComment }}
      Monitor Object Name: {{ item.monitorObjectName }}
      Resource Template Name: {{ item.resourceTemplateName }}
  with_items: "{{ parsed_data.parse_data.items }}"
  delegate_to: localhost
  run_once: true

