
---
- name: Display the collected alerts
  ansible.builtin.command: cat data.json
  delegate_to: localhost
  register: json_content
  run_once: true

- name: Create list of directories
  set_fact:
    directories: "{{ directories | default([]) + [item.monitorObjectName + '/' + item.resourceTemplateName + '/' + item.askComment] }}"
  loop: "{{ json_content.stdout['items'] }}"

- name: Display the list of directories
  debug:
    var: directories

- name: Filter items where askComment starts with 'EVT' or 'INC'
  set_fact:
    filtered_items: "{{ json_content.stdout.parse_data.items | selectattr('askComment', 'search', '^EVT|^INC') | list }}"

- name: Display filtered items
  debug:
    msg: >
      Ask Comment: {{ item.askComment }}
      Monitor Object Name: {{ item.monitorObjectName }}
      Resource Template Name: {{ item.resourceTemplateName }}
  with_items: "{{ filtered_items }}"
  delegate_to: localhost
  run_once: true

