
---
- name: Display the collected alerts
  ansible.builtin.command: cat data.json
  delegate_to: localhost
  register: json_content
  run_once: true
  
- name: Parse JSON content from the file
  set_fact:
    parsed_data: "{{ json_content.stdout | from_json }}"

- name: Filter items where askComment starts with 'EVT' or 'INC'
  set_fact:
    filtered_items: "{{ parsed_data.parse_data.items | selectattr('askComment', 'search', '^EVT|^INC') | list }}"

- name: Display filtered items
  debug:
    msg: >
      Ask Comment: {{ item.askComment }}
      Monitor Object Name: {{ item.monitorObjectName }}
      Resource Template Name: {{ item.resourceTemplateName }}
  with_items: "{{ filtered_items }}"
  delegate_to: localhost
  run_once: true

