
---
- name: Display the collected alerts
  ansible.builtin.command: cat data.json
  delegate_to: localhost
  register: json_content
  run_once: true

- name: Display the collected alerts
  debug:
    msg: "{{ json_content }}"
  
- name: Parse JSON content
  set_fact:
    parsed_data: "{{ json_content['items']}}"

- name: Display all items
  debug:
    msg: >
      Ask Comment: {{ item.askComment }}
      Monitor Object Name: {{ item.monitorObjectName }}
      Resource Template Name: {{ item.resourceTemplateName }}
  with_items: "{{ parsed_data.parse_data.items }}"
  delegate_to: localhost
  run_once: true

