---
- name: Fetch LogicMonitor alerts
  vars:
    lm_api_url: "https://{{ logicmonitor_account }}.logicmonitor.com/santaba/rest/alert/alerts"
    query_params: "size=1000"
  uri:
    url: "{{ lm_api_url }}?{{ query_params }}"
    method: GET
    headers:
      Authorization: "{{ lm_auth }}"
      Content-Type: "application/json"
    return_content: yes
  register: lm_alerts

- name: Ensure API response is successful
  fail:
    msg: "Failed to fetch alerts: {{ lm_alerts.status }}"
  when: lm_alerts.status != 200

- name: Filter alerts by group
  set_fact:
    group_alerts: "{{ lm_alerts.json.data | selectattr('groupName', 'equalto', alert_group) | list }}"

- name: Find errors in alerts
  set_fact:
    error_alerts: "{{ group_alerts | selectattr('status', 'equalto', 'error') | list }}"

- name: Display alert errors
  debug:
    msg: "Error alerts in group '{{ alert_group }}': {{ error_alerts }}"