- name: Initialize logs_status dictionary
  ansible.builtin.set_fact:
    logs_status: {}

- name: Identify errors in Log
  ansible.builtin.set_fact:
    logs_status: >-
      {{
        logs_status | union([
          'no logs found'
          if not oracle_log.stdout_lines | default([]) else
          ('not ok' if (
            'error' in (oracle_log.stdout_lines | join(' ') | lower) or
            'fail' in (oracle_log.stdout_lines | join(' ') | lower) or
            'exception' in (oracle_log.stdout_lines | join(' ') | lower)
          ) else 'ok')
        ])
      }}
  delegate_to: localhost

- name: Append logs to {{ OutputFile }}
  ansible.builtin.shell: |
    echo -e "Log Path: {{ oracle_log.item | default('') }}" >> "{{ OutputFile }}"
    echo -e "Status: {{ logs_status }}" >> "{{ OutputFile }}"
    echo -e "Host: {{ inventory_hostname | default('') }}" >> "{{ OutputFile }}"
    
    if [ -z "{{ oracle_log.stdout_lines | default([]) | join('') }}" ]; then
        echo -e "No logs collected as of {{ ansible_date_time.iso8601 }}" >> "{{ OutputFile }}"
    else
        echo -e "{{ oracle_log.stdout_lines | default([]) | join('\n') }}" >> "{{ OutputFile }}"
    fi
    
    echo -e "End of logs from {{ inventory_hostname }}\n" >> "{{ OutputFile }}"
  when: 
    - logs_status is defined
  delegate_to: localhost