- name: Fetch devices in "database" group
  ansible.builtin.uri:
    url: "https://{{ logicmonitor_company }}.logicmonitor.com/rest/device/groups"
    method: GET
    headers:
      Authorization: "Bearer {{ logicmonitor_access_token }}"
      Content-Type: "application/json"
    return_content: yes
  register: group_data

- name: Debug group data
  ansible.builtin.debug:
    var: group_data

- name: Ensure the file folder exists
  ansible.builtin.file:
    path: "./file"
    state: directory
    mode: '0755'

- name: Save the group_data to a file
  ansible.builtin.copy:
    content: "{{ group_data.json | to_nice_json }}"
    dest: "./file/group_data.json"
    mode: '0644'

- name: Extract "database" group ID
  ansible.builtin.set_fact:
    database_group_id: >-
      {{
        (group_data.json.items | selectattr('name', 'equalto', 'database') | list | first).id
          if (group_data.json.items | selectattr('name', 'equalto', 'database') | list | first) is defined
          else 'not_found'
      }}

- name: Fail if database group is not found
  ansible.builtin.fail:
    msg: "The 'database' group was not found in LogicMonitor."
  when: database_group_id == 'not_found'