---
- name: Get human-readable datetime
  ansible.builtin.command: date "+%Y-%m-%d %H:%M:%S"
  register: datetime_output
  delegate_to: localhost

- name: Set log path for each host dynamically
  set_fact:
    host_log_path: "{{ item.0.config.log_path }}"
    tail_log: "{{ item.0.tail | default(omit) }}" 
    dr_type: "{{ item.0.dr_type | default(omit) }}" 
  with_subelements:
    - "{{ lookup('vars', 'dba_automation_' + env) | dict2items | map(attribute='value') | list }}"
    - hosts
  when: inventory_hostname is match(item.1 | replace('*', '.*'))
  delegate_to: localhost

- name: mysql
  include_tasks: mysql.yaml
  when: dr_type == "mysql"

- name: mysql
  include_tasks: oracle.yaml
  when: dr_type == "oracle"