---

- name: Get human-readable datetime
  ansible.builtin.command: date "+%Y-%m-%d %H:%M:%S"
  register: datetime_output
  delegate_to: localhost

- name: Set log path for each host dynamically
  set_fact:
    host_log_path: "{{ item.0.config.log_path | default(omit) }}"
    tail_log: "{{ item.0.tail | default(omit) }}" 
    log_files_to_collect: "{{ item.0.config.log_files_to_collect | default([]) }}"
  with_subelements:
    - "{{ lookup('vars', 'dba_automation_' + env) | dict2items | map(attribute='value') | list }}"
    - hosts
  when: inventory_hostname is match(item.1 | replace('*', '.*'))
  delegate_to: localhost

- name: Verify Oracle log files exist
  ansible.builtin.stat:
    path: "{{ host_log_path }}/{{ item }}"
  register: log_file_status
  loop: "{{ log_files_to_collect }}"
  loop_control:
    label: "{{ item }}"
  when: log_files_to_collect | length > 0  # Only run if log_files_to_collect is not empty

- name: Read and display content of each log file
  ansible.builtin.shell: |
    cat {{ host_log_path }}/{{ item.item }}
  register: log_content
  with_items: "{{ log_file_status.results }}"
  changed_when: false

- name: Display combined log file contents
  ansible.builtin.debug:
    msg: |
      Logs from {{ inventory_hostname }}:
      {% for log in log_content.results %}
      - File: {{ log.item.item }}
        Content:
        {{ log.stdout }}
      {% endfor %}

