---
# tasks/main.yml

- name: Daily Monitor Logs DR PE restore log status
  shell: tail -n 10 "{{ log_path }}"
  register: log_output
  ignore_errors: yes  # Optional: In case the log file doesn't exist or there's a permission issue.
  
- name: Save logs locally for each host
  copy:
    content: "{{ log_output.stdout_lines | join('\n') }}"
    dest: "/tmp/{{ inventory_hostname }}_logs.txt"
  delegate_to: localhost  # Save the logs on the control machine

- name: Debug logs to ensure they are captured
  debug:
    msg: "Logs from host {{ inventory_hostname }}: {{ log_output.stdout_lines | default('No logs found') }}"

- name: Collect logs from all hosts and combine them into a single variable
  set_fact:
    all_logs: "{{ all_logs | default('') + '\n\nLogs from each host ' "/tmp/{{ inventory_hostname }}_logs.txt" }}"
  run_once: true  # Ensures the task runs only once and collects logs from all hosts

- name: Send mail notification with logs from all hosts
  community.general.mail:
    host: smtp.gmail.com
    port: 587
    username: "{{ email_username }}"
    password: "{{ email_password }}"
    to: panchakarlabk@gmail.com
    subject: "Daily Monitor Logs DR PE restore log status"
    body: "{{ all_logs }}"
  when: all_logs is defined
  run_once: true
