---
# tasks/main.yml

- name: Daily Monitore Logs DR PE restore log status 
  shell: tail -n 10 "{{ log_path }}"
  register: log_output
  ignore_errors: yes  # Optional: In case the log file doesn't exist or there's a permission issue.

- name: DR PE restore log status 
  debug:
    msg: "Logs from host {{ inventory_hostname }}: {{ log_output.stdout_lines | default('No logs found') }}"
    
- name: Send mail notification
  community.general.mail:
    host: smtp.gmail.com
    port: 587
    username: bharat@cxr.ai
    password: bxhg ugir udbp psqj
    to: panchakarlabk@gmail.com
    subject: Logs from /var/log/messages
    body: |
      Host: {{ inventory_hostname }}
      Here are the logs from {{ log_path }}:
      {% for line in log_output.stdout_lines %}
      {{ line }}
      {% endfor %}
  when: log_output.stdout_lines is defined 
