---
# tasks/main.yml

# Step 1: Start DR PE restore check
- name: Start DR PE restore check
  debug:
    msg: "Start check DR PE restore at: {{ ansible_date_time.iso8601 }}"
# tasks/main.yml

- name: Daily Monitor Logs DR PE restore log status
  shell: tail -n 10 "{{ log_path }}"  >> /tmp/all_logs.txt 2>&1 
  ignore_errors: yes  # Optional: In case the log file doesn't exist or there's a permission issue.
  delegate_to: localhost

- name: Display the content of all_logs.txt
  command: cat /tmp/all_logs.txt
  delegate_to: localhost  # Run the task on the control machine
  register: all_logs
  
# - name: Dr Pe logs 
#   ansible.builtin.debug:
#      msg: "{{ log_output }}"
#   register: log_output
#   delegate_to: localhost
# - name: Append logs to a single file on localhost
#   lineinfile:
#     path: "/tmp/all_logs.txt"
#     line: |
#       ### Logs from host: {{ inventory_hostname }} ###
#       {% if log_output.stdout_lines %}
#       {{ log_output.stdout_lines | join('\n') }}
#       {% else %}
#       No logs found.
#       {% endif %}
#     create: yes
#     insertafter: EOF  # Ensures the new content is appended to the end of the file
#   delegate_to: localhost  # Run this task on the control machine
