---
# tasks/main.yml

- name: Display /var/log/messages logs
  shell: tail -n 10 /var/log/messages
  register: log_output
  ignore_errors: yes  # Optional: In case the log file doesn't exist or there's a permission issue.

- name: Show the log output
  debug:
    msg: "{{ log_output.stdout_lines }}"

# - name: Run a shell command and capture output
#   shell: echo "This is a success message"
#   register: command_output

# - name: Debug command output
#   debug:
#     var: command_output.stdout_lines


- name: Send mail notification
  community.general.mail:
    host: smtp.gmail.com
    port: 587
    username: bharat@cxr.ai
    password: bxhg ugir udbp psqj
    to: panchakarlabk@gmail.com
    subject: Logs from /var/log/messages
    body: |
      Here are the logs from /var/log/messages:
      {% for line in log_output.stdout_lines %}
      {{ line }}
      {% endfor %}
  when: log_output.stdout_lines is defined 

