---
# Step 1: Collect logs and append them to a single file
- name: Daily Monitor Logs DR PE restore log status
  ansible.builtin.shell: | 
     tail "{{ log_path }}" | grep "$(date +%Y/%m/%d)"
  ignore_errors: yes  # Continue even if there are issues
  register: all_logs

- name: Append logs with CET time
  ansible.builtin.shell: |
    echo "=== DR PE {{ ansible_date_time.iso8601 | to_datetime | strftime('%Y-%m-%d %H:%M:%S') }} CET ===" >> /tmp/all_logs_collected.txt
    if [ -z "{{ all_logs.stdout_lines | join('') }}" ]; then
      echo "No logs collected as of {{ ansible_date_time.iso8601 | to_datetime | strftime('%Y-%m-%d %H:%M:%S') }} CET" >> /tmp/all_logs_collected.txt
    else
      echo "{{ all_logs.stdout_lines | join('\n') }}" >> /tmp/all_logs_collected.txt
    fi
    echo "=== End of logs from {{ inventory_hostname }} ===" >> /tmp/all_logs_collected.txt
  delegate_to: localhost

  # Ensure this runs on the controller

# Step 3: Check for errors in logs
- name: Identify errors in logs
  ansible.builtin.set_fact:
    logs_status: >-
      {% if not all_logs.stdout_lines %}
      no logs found
      {% elif 'error' in (all_logs.stdout_lines | join(' ') | lower) %}
      not ok
      {% else %}
      ok
      {% endif %}
  run_once: true
  delegate_to: localhost

# Step 5: Display the collected logs
- name: Display the collected logs
  ansible.builtin.command: cat /tmp/all_logs_collected.txt
  delegate_to: localhost
  register: consolidated_logs
  run_once: true

# Step 6: Render the email template
- name: Render the email body template
  template:
    src: email_template.j2
    dest: /tmp/email_body.txt
  vars:
    logs_status: "{{ logs_status }}"
    consolidated_logs: "{{ consolidated_logs.stdout_lines }}"
  run_once: true
  delegate_to: localhost


- name: logs_status
  ansible.builtin.debug:
    msg:  "{{ logs_status }}"
  run_once: true
  delegate_to: localhost

# # Step 7: Send Daily Monitor Logs mail notification
- name: Send Daily Monitor Logs mail notification
  community.general.mail:
    host: smtp.gmail.com
    port: 587
    username: "{{ email_username }}"
    password: "{{ email_password }}"
    to: panchakarlabk@gmail.com
    subject: Daily Monitor Logs DR PE restore log status
    body: "{{ lookup('file', '/tmp/email_body.txt') }}"
  when: consolidated_logs.stdout_lines is defined 
  run_once: true
  delegate_to: localhost



