---
# Step 1: Start DR PE restore check
- name: Start DR PE restore check
  debug:
    msg: "Start check DR PE restore at: {{ ansible_date_time.iso8601 }}"

# Step 2: Collect logs and append them to a single file
- name: Daily Monitor Logs DR PE restore log status
  shell: | 
     echo "=== Logs from {{ inventory_hostname }} ===" 
     tail -n 10 "{{ log_path }}" 
  vars:
    log_path: "/var/log/messages"  # Default path for logs; change if necessary
  ignore_errors: yes  # Continue even if there are issues
  register: all_logs
  #delegate_to: localhost  # Collect logs on the control machine

# Step 3: Append logs to a file on the controller
- name: Append logs to a central file on the controller
  copy:
    content: |
      === Logs from {{ inventory_hostname }} ===
      {{ all_logs.stdout | default('No logs collected') }}
      === End of logs from {{ inventory_hostname }} ===
    dest: "/tmp/all_logs_collected.txt"
    remote_src: false
    append: true  # Append logs from each host to the same file
  delegate_to: localhost  # Run this task on the controller

# Step 4: Display the collected logs
- name: Display the collected logs
  command: cat /tmp/all_logs_collected.txt
  delegate_to: localhost
  register: consolidated_logs

# Step 5: Show the logs in the playbook output
- name: Show logs in the playbook output
  debug:
    var: consolidated_logs.stdout