---
# tasks/main.yml

# Step 1: Start DR PE restore check
- name: Start DR PE restore check
  debug:
    msg: "Start check DR PE restore at: {{ ansible_date_time.iso8601 }}"

# Step 2: Collect logs from host1 using slurp (base64 encoded content)
- name: Collect logs from host1
  slurp:
    src: "{{ log_dir }}/{{ log_file }}"
  register: host1_logs
  delegate_to: "{{ host1 }}"
  run_once: true

# Step 3: Collect logs from host2 using slurp (base64 encoded content)
- name: Collect logs from host2
  slurp:
    src: "{{ log_dir }}/{{ log_file }}"
  register: host2_logs
  delegate_to: "{{ host2 }}"
  run_once: true

# Step 4: Append logs from host1 to a single output file on localhost
- name: Append logs from host1 to the output file
  copy:
    content: |
      ### Logs from host1 ###
      {{ host1_logs.content | b64decode }}
    dest: "{{ out_dir }}/{{ out_file }}"
    append: yes
  delegate_to: localhost
  run_once: true

# Step 5: Append logs from host2 to the output file on localhost
- name: Append logs from host2 to the output file
  copy:
    content: |
      ### Logs from host2 ###
      {{ host2_logs.content | b64decode }}
    dest: "{{ out_dir }}/{{ out_file }}"
    append: yes
  delegate_to: localhost
  run_once: true

# Step 6: Display the contents of the output file
- name: Display the content of /tmp/all_logs.txt
  command: cat {{ out_dir }}/{{ out_file }}
  delegate_to: localhost
  run_once: true
