---
# tasks/main.yml

# Step 1: Start DR PE restore check
- name: Start DR PE restore check
  debug:
    msg: "Start check DR PE restore at: {{ ansible_date_time.iso8601 }}"

# Step 2: Collect logs from host1 using fetch
- name: Collect logs from host1
  fetch:
    src: "{{ log_dir }}/{{ log_file }}"
    dest: "/tmp/{{ inventory_hostname }}_{{ out_file }}"
    flat: yes
  delegate_to: "{{ host1 }}"
  run_once: true

# Step 3: Collect logs from host2 using fetch
- name: Collect logs from host2
  fetch:
    src: "{{ log_dir }}/{{ log_file }}"
    dest: "/tmp/{{ inventory_hostname }}_{{ out_file }}"
    flat: yes
  delegate_to: "{{ host2 }}"
  run_once: true

# Step 4: Append logs from host1 to the output file on localhost
- name: Append logs from host1 to the output file
  copy:
    src: "/tmp/{{ host1 }}_{{ out_file }}"
    dest: "{{ out_dir }}/{{ out_file }}"
    append: yes
  delegate_to: localhost
  run_once: true

# Step 5: Append logs from host2 to the output file on localhost
- name: Append logs from host2 to the output file
  copy:
    src: "/tmp/{{ host2 }}_{{ out_file }}"
    dest: "{{ out_dir }}/{{ out_file }}"
    append: yes
  delegate_to: localhost
  run_once: true

# Step 6: Display the contents of the output file
- name: Display the content of the log file
  command: cat {{ out_dir }}/{{ out_file }}
  delegate_to: localhost
  run_once: true
