---
- name: Render the email body template
  template:
    src: email_template.j2
    dest: /tmp/email_body.txt
  delegate_to: localhost
  when: email_body is defined
    
- name: Send email notification
  community.general.mail:
    host: smtp.gmail.com
    port: 587
    username: "{{ email_username }}"
    password: "{{ email_password }}"
    to: "{{ email_recipient }}"
    subject: "{{ email_subject }}"
    body: "{{ lookup('file', '/tmp/email_body.txt') }}"
    subtype: html
  when: email_body is defined
  run_once: true
  delegate_to: localhost
