dba_automation_dev:
  process_001_mysql:
    config:
      log_path: "/home/bharat/logs/logs.txt"
    hosts:
      - ip: 192.168.162.136
  process_002_orcale:
    config:
      log_path: "/home/bharat/logs.log"
    hosts:
      - ip: 192.168.162.128
        hostname: rhel8.lb.uk
        env: prod
      - ip: 192.168.162.130
    tail: 25

dba_automation_prod:
  process_001_mysql:
    config:
      log_path: "/home/bharat/logs/logs.txt"
    hosts:
      - 192.168.162.130
  process_002_orcale:
    config:
      log_path: "/home/bharat/logs.log"
    hosts:
      - 192.168.162.135
    tail: 25

ignore_alerts_rules:
  - code: "rule_001"
    decription: "dummy stuff not DBA topic"
    ignore_if:
      - monitorObjectName: "DatabaseServer*"
  - code: "rule_002"
    decription: "app/business alerts"
    ignore_if:
      - resourceTemplateName: "Apache*"
  

