dba_automation:
  process_001_mysql:
    config:
      log_path: "/home/bharat/logs/logs.txt"
    hosts:
      - 192.168.162.128
      # - 192.168.162.136  # Assuming you meant different hosts here, otherwise it will be duplicate
  process_002_orcale:
    config:
      log_path: "/home/bharat/logs.log"
    hosts:
      - 192.168.162.136

ignore_alerts_rules:
  - code: "rule_001"
    decription: "dummy stuff not DBA topic"
    ignore_if:
      - monitorObjectName: "DatabaseServer1*"
      - monitorObjectName: "CacheServer3"
      - askComment: "OTHER789"
  - code: "rule_002"
    decription: "app/business alerts"
    ignore_if:
      - resourceTemplateName: "Apache*"

