dba_host_list:
  - hostname: 192.168.162.128
    friendlyname: "rhel 9 host"

dba_automation_prod:
  process_001_mysql:
    config:
      log_path: "/home/bharat/logs/logs.txt"
    hosts:
      - 192.168.162.136
  process_002_mysql:
    config:
      log_path: "/home/bharat/logs/logs.txt"
    hosts:
      - 192.168.162.125
    tail: 25
    type: mysql
  process_002_orecle:
    config:
      log_path: "/home/bharat/logs"  # Base directory where logs are stored
      log_files_to_collect:
        - logs1.txt
        - logs2.txt
        - logs3.txt
    type: oracle
    tail: 25
    hosts:
      - 192.168.162.128

dba_automation_dev:
  process_001_mysql:
    config:
      log_path: "/home/bharat/logs/logs.txt"
    hosts:
      - 192.168.162.130
  process_002_orecle:
    config:
      log_path: "/home/bharat/logs.log"
    hosts:
      - 192.168.162.135
    tail: 25

ignore_alerts_rules:
  - code: "rule_001"
    decription: "dummy stuff not DBA topic"
    ignore_if:
      - monitorObjectName: "DatabaseServer*"
  - code: "rule_002"
    decription: "app/business alerts"
    ignore_if:
      - resourceTemplateName: "Apache*"
  

