dba_automation:
  process_001_send:
    config:
      log_path: "/home/bharat/logs/logs.txt"
    hosts:
      - 192.168.162.128
      - 192.168.162.130  # Assuming you meant different hosts here, otherwise it will be duplicate
  process_002_send_postcard_to_santa_claus:
    config:
      log_path: "/home/bharat/logs/logs.txt"
    hosts:
      - 192.168.162.128
