---
- name: This is my test plabook 
  hosts: "{{ targets }}"
  become: false
  vars_files: 
    - host_config.yml    # Load the configuration file
  roles:
    #- restore_status
    # - logicmonitor_status
    - restore_status_orecle

  # # Conditional role inclusion
  # tasks:
  #   - name: Include send_email_notification role if conditions are met
  #     include_role:
  #       name: send_email_notification
  #     when: 
  #       - restore_status_result is defined
  #       - restore_status_result.success
        # - logicmonitor_status_result is defined
        # - logicmonitor_status_result.success
