---
- name: This is my test plabook 
  hosts: "{{ targets }}"
  become: true
  vars_files: 
    - host_config.yml    # Load the configuration file
  roles:
    - restore_status
    # - logicmonitor_status
    - send_email_notification 
