---
- name: This is my test plabook 
  hosts: "{{ targets }}"
  become: true
  vars_files: 
    - host_config.yml    # Load the configuration file
  roles:
    - role: restore_status
      vars:
        host_config: "{{ host_config }}"
    - send_email_notification 

  tasks:

  - name: Ensure log path is set for each host
    debug:
      msg: "Log path for {{ inventory_hostname }} is {{ host_config[inventory_hostname].log_path }}"
