---
- name: This is my test plabook 
  hosts: "{{ targets }}"
  become: true
  vars_files: 
    - host_config.yml    # Load the configuration file
  roles:
    - restore_status
    - logicmonitor_status
    
  handlers:
    - name: send_email_notification
      import_tasks: "./roles/send_email_notification/tasks/main.yml"
      when: 
        - restore_status_result is defined and restore_status_result.success 
        - logicmonitor_status_result is defined and logicmonitor_status_result.success
