---
- name: This is my test plabook 
  hosts: "{{ targets }}"
  become: true
  vars_files: 
    - host_config.yml    # Load the configuration file
  roles:
    - role: restore_status
      vars:
        host_config: "{{ host_config }}"
    - send_email_notification 

  tasks:
  - name: Debug hosts_config variable
    debug:
      var: "{{ host_config }}"