---
- name: This is my test plabook 
  hosts: "{{ targets }}"
  become: true
  vars_files:
  - host_config.yml  # Load the configuration file
  roles:
    - { role: ./../roles/restore_status }
    - { role: ./../roles/send_email_notification }